jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H 4.178.136.107 >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: ssh -i ~/.ssh/deploy_key hngx@4.178.136.107 "echo Connected successfully!"

